version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 1.10.0
    - 1.9.0
    - 2.0.0
    - 2.1.0
    - 2.2.0
  - dependency-name: styled-components
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-catch-links
    versions:
    - 2.9.0
  - dependency-name: gatsby-remark-embedder
    versions:
    - 4.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
