backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
  - name: languages
    label: Languages
    folder: content/languages
    create: false
    delete: false
    fields:
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "Code"
      name: "code"
      widget: "string"
    - label: "Icon"
      name: "icon"
      default: false
      widget: "image"
    - label: "Predefinida"
      name: "isDefault"
      default: false
      widget: "boolean"
  - name: settings
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - label: "English"
            name: en
            widget: "object"
            fields:
              - label: Title
                name: title
                widget: string
          - label: "Portugues"
            name: pt
            widget: "object"
            fields:
              - label: Title
                name: title
                widget: string
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
          - {
              label: Languages,
              name: languages,
              delete: false,
              widget: list,
              fields: [
                 { label: Language, name: language, widget: "string" },
                 { label: Code, name: code, widget: "string" }
                ]
          }
  - name: menus
    label: Menus
    extension: json
    format: json
    folder: content/menus
    create: true
    widget: "object"
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: "string" }
      - label: "English"
        name: en
        widget: "object"
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - label: Display
                name: display
                widget: markdown
              - label: Link
                name: link
                widget: text
              - label: Description
                name: description
                widget: text
                required: false
              - label: Enabled
                name: enabled
                widget: boolean
                deafault: true
      - label: "Português"
        name: pt
        widget: "object"
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - label: Display
                name: display
                widget: markdown
              - label: Link
                name: link
                widget: text
              - label: Description
                name: description
                widget: text
                required: false
        # - label: Aliases
        #   name: aliases
        #   widget: list
        #   fields:
        #     - label: Link
        #       name: link
        #       widget: string
        #     - label: Permanent
        #       name: permanent
        #       widget: boolean
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{slug}}-{{language}}-{{year}}-{{month}}-{{day}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: "Language"
        name: "language"
        widget: "relation"
        collection: "languages"
        searchFields: ["Title"]
        valueField: "code"
        default: 'en'
        required: true
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["Published", "Featured", "Draft"]
        default: "Published"
      - { label: Date / Order, name: date, widget: date }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        required: false
        name: tags
        widget: list
      - label: "Meta"
        required: false
        name: "meta"
        widget: "object"
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }
  - name: tours
    extension: json
    format: json
    label: Tours
    folder: src/pages/tours
    create: true
    slug: "{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: tour-page
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: markdown
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
      - label: Waypoints
        name: waypoints
        widget: list
        fields:
          - label: Point
            name: lat
            widget: map
  - name: toursj
    extension: json
    format: json
    label: Toursj
    folder: src/pages/toursj
    create: true
    slug: "{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: tour-page
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: markdown
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
      - label: Waypoints
        name: waypoints
        widget: list
        fields:
          - label: Point
            name: lat
            widget: map
  - name: home_banners
    label: Home Banners
    folder: src/banners/home
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
  - name: pages
    label: Pages
    delete: false
    files:
      - file: content/pages/about/index.en.md
        label: AboutEN
        name: aboutEN
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about-page
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
      - file: content/pages/about/index.pt.md
        label: AboutPT
        name: aboutPT
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about-page
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
#      - file: content/pages/products/index.md
        # label: Products Page
        # name: products
        # fields:
        #   - label: Template Key
        #     name: templateKey
        #     widget: hidden
        #     default: product-page
        #   - label: Title
        #     name: title
        #     widget: string
        #   - label: Image
        #     name: image
        #     widget: image
        #   - label: Heading
        #     name: heading
        #     widget: string
        #   - label: Description
        #     name: description
        #     widget: string
        #   - label: Intro
        #     name: intro
        #     widget: object
        #     fields:
        #       - label: Heading
        #         name: heading
        #         widget: string
        #       - label: Description
        #         name: description
        #         widget: text
        #       - label: Blurbs
        #         name: blurbs
        #         widget: list
        #         fields:
        #           - label: Image
        #             name: image
        #             widget: image
        #           - label: Text
        #             name: text
        #             widget: text
        #   - label: Main
        #     name: main
        #     widget: object
        #     fields:
        #       - label: Heading
        #         name: heading
        #         widget: string
        #       - label: Description
        #         name: description
        #         widget: text
        #       - label: Image1
        #         name: image1
        #         widget: object
        #         fields:
        #           - label: Image
        #             name: image
        #             widget: image
        #           - label: Alt
        #             name: alt
        #             widget: string
        #       - label: Image2
        #         name: image2
        #         widget: object
        #         fields:
        #           - label: Image
        #             name: image
        #             widget: image
        #           - label: Alt
        #             name: alt
        #             widget: string
        #       - label: Image3
        #         name: image3
        #         widget: object
        #         fields:
        #           - label: Image
        #             name: image
        #             widget: image
        #           - label: Alt
        #             name: alt
        #             widget: string
        #   - label: Testimonials
        #     name: testimonials
        #     widget: list
        #     fields:
        #       - label: Quote
        #         name: quote
        #         widget: string
        #       - label: Author
        #         name: author
        #         widget: string
        #   - label: Full_image
        #     name: full_image
        #     widget: image
        #   - label: Pricing
        #     name: pricing
        #     widget: object
        #     fields:
        #       - label: Heading
        #         name: heading
        #         widget: string
        #       - label: Description
        #         name: description
        #         widget: string
        #       - label: Plans
        #         name: plans
        #         widget: list
        #         fields:
        #           - label: Plan
        #             name: plan
        #             widget: string
        #           - label: Price
        #             name: price
        #             widget: string
        #           - label: Description
        #             name: description
        #             widget: string
        #           - label: Items
        #             name: items
        #             widget: list
      - file: content/pages/home/index.en.md
        label: "Home EN"
        name: homeEN
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: home-page
          - label: Title
            name: title
            widget: string
          - label: TourSection
            name: toursection
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: markdown
              - label: Description
                name: description
                widget: markdown
              - label: DescriptionAfter
                name: descriptionafter
                widget: markdown
              - label: Tours
                name: tours
                widget: list
                fields:
                  - label: Tour
                    name: tour
                    widget: string
          - label: Body
            name: body
            widget: markdown
          - label: "Banners"
            name: "banners"
            widget: "list"
            required: false
            fields:
              - label: "Banners"
                name: "banners"
                widget: "relation"
                collection: "banners"
                searchFields: ["title"]
                valueField: "path"
      - file: content/pages/home/index.pt.md
        label: "Home PT"
        name: homePT
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: home-page
          - label: Title
            name: title
            widget: string
          - label: TourSection
            name: toursection
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: markdown
              - label: Description
                name: description
                widget: markdown
              - label: DescriptionAfter
                name: descriptionafter
                widget: markdown
              - label: Tours
                name: tours
                widget: list
                fields:
                  - label: Tour
                    name: tour
                    widget: string
          - label: Body
            name: body
            widget: markdown
  - name: banners
    label: Banners
    editor:
      preview: false
    folder: content/banners
    slug: "{{title-language}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: key, name: key, widget: uuid }
      - { label: Template, name: template, widget: hidden, default: Banner }
      - { label: Title, name: title, widget: markdown }
      - { label: Language, name: language, widget: markdown }
      - { label: Description, name: description, widget: markdown }
      - {
          label: GoTo,
          name: goto,
          widget: object,
          fields:
            [
              { label: Link, name: link, widget: string },
              { label: LinkText, name: linktext, widget: string },
              { label: LinkTitle, name: linktitle, widget: string },
            ],
        }
      - { label: Image, name: image, widget: image, required: true }
      # - label: 'Meta'
      #   required: false
      #   name: 'meta'
      #   widget: 'object'
      #   fields:
      #     - { label: Title, name: title, widget: string, required: false }
      #     - {
      #         label: Description,
      #         name: description,
      #         widget: text,
      #         required: false,
      #       }
      #     - {
      #         label: Canonical Link,
      #         name: canonicalLink,
      #         widget: string,
      #         required: false,
      #       }
      #     - { label: Noindex, name: noindex, widget: boolean, required: false }
